// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dprtbwbfjxslpriicukl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwcnRid2JmanhzbHByaWljdWtsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcxNzU4NDAsImV4cCI6MjA3Mjc1MTg0MH0._frG2fepXcn3mMCEqWKt4p4LK4SFwK-D2178WpuhWXM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});